#!/usr/bin/env bash
# rice-sync — copy the live rice from $HOME into this repo, check it for secrets,
# then commit and push.
#   rice-sync            sync, commit, push
#   rice-sync --dry-run  sync and show the diff, no commit
# Machine-only files stay out: hypr/monitors.lua, hypr/devices.lua, waybar/config.local.json.
set -euo pipefail

REPO=$(cd "$(dirname "$(readlink -f "$0")")" && pwd)
DST="$REPO/home"
DRY=0
[ "${1:-}" = "--dry-run" ] && DRY=1

# What makes up the rice, relative to $HOME. Directories are copied whole minus EXCLUDES.
PATHS=(
    .config/hypr
    .config/waybar/config.base.json
    .config/waybar/scripts
    .config/quickshell
    .config/kitty/kitty.conf
    .config/fish
    .config/histui/histuid.toml
    .config/systemd/user/histuid.service
    .config/systemd/user/portal-restart.service
    .config/systemd/user/portal-restart.timer
    .config/systemd/user/xdg-desktop-portal-hyprland.service.d
    .config/systemd/user/xdg-desktop-portal.service.d
    ".config/Code - OSS/User/settings.json"
    ".config/Code - OSS/User/keybindings.json"
    .config/gtk-3.0/settings.ini
    .config/gtk-4.0/settings.ini
    .icons/default/index.theme
    .local/share/icons/WhiteCat
    .local/bin/changetheme
    .local/bin/theme-picker
    .local/bin/launcher
    .local/bin/shot
    .local/bin/shots-gallery
    .local/bin/power-menu
    .local/bin/help-panel
    .local/bin/notif-panel
    .local/bin/screen-fx
    .local/bin/mouse-sens
    .local/bin/portal-restart
    .local/bin/neohtop
    .claude/statusline.sh
)

# Generated by themegen/changetheme, machine-specific, or backups.
EXCLUDES=(
    --exclude=.config/hypr/build
    --exclude=.config/hypr/hyprlang-backup
    --exclude=.config/hypr/monitors.lua
    --exclude=.config/hypr/devices.lua
    --exclude=.config/hypr/palette.lua
    --exclude=.config/hypr/palette.json
    --exclude=.config/hypr/current-theme
    --exclude=.config/hypr/current-wallpaper
    --exclude=.config/hypr/hyprlock-colors.conf
    --exclude=.config/hypr/theme.lua
    --exclude=.config/hypr/hyprlock.conf
    --exclude=.config/hypr/themes/whitecat-cursor.osk
    --exclude=.config/fish/functions/neohtop-dev.fish
    --exclude=__pycache__
    --exclude='*.bak*'
    --exclude='*.pyc'
)

cd "$HOME"
missing=()
present=()
for p in "${PATHS[@]}"; do
    if [ -e "$p" ]; then present+=("$p"); else missing+=("$p"); fi
done
[ ${#missing[@]} -eq 0 ] || printf 'нет на этой машине, пропускаю: %s\n' "${missing[@]}"

rm -rf "$DST"
mkdir -p "$DST"
tar -cf - "${EXCLUDES[@]}" "${present[@]}" | tar -C "$DST" -xf -

# Absolute paths (waybar CSS needs file:// URLs) become a placeholder the installer fills in.
grep -rIl --null "$HOME" "$DST" | xargs -0 -r sed -i "s|$HOME|__HOME__|g"

# Refuse to publish anything that looks like a secret.
SECRET_RE='sk-ant-[A-Za-z0-9_-]{10,}|gh[pousr]_[A-Za-z0-9]{20,}|github_pat_[A-Za-z0-9_]{20,}|BEGIN [A-Z ]*PRIVATE KEY|"(accessToken|refreshToken)"[[:space:]]*:[[:space:]]*"|AKIA[0-9A-Z]{16}'
if hits=$(grep -rIEn "$SECRET_RE" "$REPO" --exclude-dir=.git --exclude=sync.sh); then
    echo "СТОП: похоже на секрет, ничего не отправляю:" >&2
    echo "$hits" >&2
    exit 1
fi
# A file this size is either a mistake or will hit GitHub's 100 MB limit.
if big=$(find "$REPO" -path "$REPO/.git" -prune -o -type f -size +50M -print | grep .); then
    echo "СТОП: слишком большие файлы:" >&2
    echo "$big" >&2
    exit 1
fi

cd "$REPO"
git add -A
if git diff --cached --quiet; then
    echo "Изменений нет."
    exit 0
fi
git diff --cached --stat | tail -n 15
if [ "$DRY" = 1 ]; then
    git reset -q
    echo "(--dry-run: ничего не закоммичено)"
    exit 0
fi
git commit -qm "sync: $(date '+%Y-%m-%d %H:%M')"
git push -q origin main
echo "Отправлено: $(git log -1 --format='%h %s')"
