#!/usr/bin/env python3
"""Generate app configs from ~/.config/hypr/themes/<name>/palette.json.

  themegen.py apply <theme> [--wallpaper PATH]   write configs for the active theme
  themegen.py build                              regenerate artifacts that bundle every theme
                                                 (drift themes, Code - OSS extension, neoHtop)
"""
import io
import json
import math
import os
import re
import shlex
import shutil
import subprocess
import sys
import time
import zipfile
from pathlib import Path

from PIL import Image, ImageEnhance, ImageFilter

HOME = Path.home()
HYPR = HOME / ".config/hypr"
THEMES = HYPR / "themes"
GENERATED = "Generated by ~/.config/hypr/scripts/themegen.py, do not edit by hand."

VSCODE_EXT_ID = "larion.hypr-themes"
# Bumped on every build so a running Code - OSS notices the reinstalled themes.
VSCODE_EXT_VERSION = f"1.0.{int(time.time()) // 60}"


# ---------- colors ----------

def rgb(c):
    c = c.lstrip("#")
    return tuple(int(c[i:i + 2], 16) for i in (0, 2, 4))


def hexc(t):
    return "#" + "".join(f"{max(0, min(255, round(v))):02x}" for v in t)


def mix(a, b, t):
    """t=0 -> a, t=1 -> b."""
    ra, rb = rgb(a), rgb(b)
    return hexc(tuple(x + (y - x) * t for x, y in zip(ra, rb)))


def alpha(c, a):
    return f"{c}{round(a * 255):02x}"


def css_rgba(c, a):
    r, g, b = rgb(c)
    return f"rgba({r}, {g}, {b}, {a})"


# ---------- palettes ----------

def load(name):
    data = json.loads((THEMES / name / "palette.json").read_text())
    data["c"] = data["colors"]
    return data


def all_themes():
    return sorted(p.parent.name for p in THEMES.glob("*/palette.json"))


def write(path, text):
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.is_symlink():
        path.unlink()
    path.write_text(text)


# ---------- per-theme outputs ----------

def gen_hypr(t):
    c = t["c"]
    write(HYPR / "palette.lua", f"""-- Палитра темы «{t['name']}». {GENERATED}
return {{
    active   = "{c['accent']}",
    active2  = "{c['accent2']}",
    inactive = "{alpha(c['muted'], 0.67)}",
}}
""")
    # Read by the Quickshell screenshot overlay and anything else that wants the full palette.
    write(HYPR / "palette.json", json.dumps({k: v for k, v in t.items() if k != "c"}, indent=2) + "\n")
    write(HYPR / "current-theme", t["name"] + "\n")


def gen_css_palette(t):
    c = t["c"]
    body = "".join(f"@define-color {k:<8}{v};\n" for k, v in c.items())
    text = f"/* Палитра темы «{t['name']}». {GENERATED} */\n{body}"
    write(HOME / ".config/waybar/wallust-colors.css", text)
    write(HOME / ".config/histui/colors.css", text)


def deep_merge(base, over):
    out = dict(base)
    for k, v in over.items():
        out[k] = deep_merge(out[k], v) if isinstance(v, dict) and isinstance(out.get(k), dict) else v
    return out


def gen_waybar(t):
    # Shared modules live in config.base.json; a theme may override parts of it in waybar.json.
    base_path = HOME / ".config/waybar/config.base.json"
    if not base_path.exists():
        return
    cfg = json.loads(base_path.read_text())
    over = THEMES / t["name"] / "waybar.json"
    if over.exists():
        cfg = deep_merge(cfg, json.loads(over.read_text()))
    # Machine-specific bits (outputs in persistent-workspaces, ...), not part of the rice repo.
    local = HOME / ".config/waybar/config.local.json"
    if local.exists():
        # One level deep: a module option given here replaces the shared one as a whole.
        for mod, opts in json.loads(local.read_text()).items():
            cfg[mod] = {**cfg[mod], **opts} if isinstance(opts, dict) and isinstance(cfg.get(mod), dict) else opts
    write(HOME / ".config/waybar/config.json", json.dumps(cfg, indent=4, ensure_ascii=False) + "\n")


def gen_kitty(t):
    c = t["c"]
    bg, fg = c["bg"], c["fg"]
    ansi = [c["bg2"], c["crit"], c["good"], c["warn"], c["accent"], c["accent3"], c["accent2"], fg]
    bright = [c["muted"]] + [mix(x, "#ffffff", 0.22) for x in ansi[1:7]] + [mix(fg, "#ffffff", 0.5)]
    lines = [f"# Тема «{t['name']}». {GENERATED}",
             f"foreground {fg}", f"background {bg}",
             f"cursor {c['accent']}", f"cursor_text_color {bg}",
             f"selection_foreground {fg}", f"selection_background {mix(c['accent'], bg, 0.55)}",
             f"url_color {c['accent2']}",
             f"active_border_color {c['accent']}", f"inactive_border_color {c['muted']}",
             f"active_tab_foreground {bg}", f"active_tab_background {c['accent']}",
             f"inactive_tab_foreground {c['muted']}", f"inactive_tab_background {c['bg2']}",
             f"tab_bar_background {bg}", f"mark1_background {c['accent2']}"]
    lines += [f"color{i} {col}" for i, col in enumerate(ansi + bright)]
    write(HOME / ".config/kitty/theme.conf", "\n".join(lines) + "\n")
    # kitty re-reads its config on SIGUSR1, so open windows pick the colours up at once.
    subprocess.run(["pkill", "-USR1", "-x", "kitty"], check=False)


def gen_hyprlock(t, wallpaper):
    c = t["c"]
    lines = [f"# Палитра темы «{t['name']}». {GENERATED}"]
    for k, v in c.items():
        h = v.lstrip("#")
        # hyprlang cannot append alpha to a variable, so ship the variants themes need.
        lines.append(f"${k} = rgb({h})")
        lines.append(f"${k}_glass = rgba({h}cc)")
        lines.append(f"${k}_soft = rgba({h}55)")
    lines.append(f"$font = {t['font']}")
    lines.append(f"$display_font = {t['display']}")
    lines.append(f"$theme_dir = {THEMES / t['name']}")
    if wallpaper:
        lines.append(f"$wallpaper = {wallpaper}")
    else:
        # hyprlock needs some value; fall back to a screenshot of the current screen.
        lines.append("$wallpaper = screenshot")
    write(HYPR / "hyprlock-colors.conf", "\n".join(lines) + "\n")
    theme_conf = THEMES / t["name"] / "hyprlock.conf"
    link = HYPR / "hyprlock.conf"
    if theme_conf.exists():
        if link.exists() or link.is_symlink():
            link.unlink()
        link.symlink_to(theme_conf)


GTK_COMMON = """
window, .background {{ background-color: {bg}; color: {fg}; }}
headerbar, .titlebar, headerbar.titlebar {{
    background: {bg2}; color: {fg}; border-color: {border}; box-shadow: none;
}}
headerbar:backdrop, .titlebar:backdrop {{ background: {bg}; color: {muted}; }}
.sidebar, placessidebar, placessidebar list, placessidebar row, .navigation-sidebar {{
    background-color: {sidebar}; color: {fg};
}}
.view, iconview, treeview.view, textview text, list, list row, gridview, columnview {{
    background-color: {bg}; color: {fg};
}}
.view:selected, iconview:selected, treeview.view:selected, list row:selected,
placessidebar row:selected, .navigation-sidebar row:selected, *:selected {{
    background-color: {sel}; color: {fg};
}}
.view:hover, list row:hover, placessidebar row:hover {{ background-color: {hover}; }}
/* The drag-selection box is drawn with the view's own style context, so without this it
   inherits the opaque .view background above and covers the files as a solid square. */
.view.rubberband, .rubberband, rubberband, iconview.rubberband, treeview.view.rubberband,
flowbox rubberband, gridview > rubberband, columnview > rubberband {{
    background-color: {rubber}; border: 1px solid {accent};
}}
entry, spinbutton, searchbar entry {{
    background-color: {bg2}; color: {fg}; border-color: {border}; caret-color: {accent};
}}
entry:focus, spinbutton:focus {{ border-color: {accent}; box-shadow: inset 0 0 0 1px {accent}; }}
button {{ background-image: none; background-color: {bg2}; color: {fg}; border-color: {border}; }}
button:hover {{ background-color: {hover}; }}
button:checked, button:active {{ background-color: {sel}; }}
button.suggested-action {{ background-color: {accent}; color: {bg}; }}
button.destructive-action {{ background-color: {crit}; color: {bg}; }}
menu, .menu, .context-menu, popover, popover > contents, popover.background {{
    background-color: {bg2}; color: {fg};
}}
menu menuitem:hover, popover modelbutton:hover, .menu menuitem:hover {{
    background-color: {sel}; color: {fg};
}}
tooltip, tooltip.background {{ background-color: {bg2}; color: {fg}; border: 1px solid {border}; }}
scrollbar slider {{ background-color: {scroll}; }}
scrollbar slider:hover {{ background-color: {accent}; }}
link, *:link {{ color: {accent}; }}
progressbar progress, scale highlight, levelbar block.filled {{ background-color: {accent}; }}
switch:checked {{ background-color: {accent}; }}
check:checked, radio:checked {{ background-color: {accent}; color: {bg}; }}
statusbar, .statusbar {{ background-color: {bg2}; color: {muted}; }}
"""


def gen_gtk(t):
    c = t["c"]
    v = {
        "bg": c["bg"], "bg2": c["bg2"], "fg": c["fg"], "muted": c["muted"],
        "accent": c["accent"], "crit": c["crit"],
        "sidebar": mix(c["bg"], c["bg2"], 0.6),
        "border": mix(c["bg2"], c["muted"], 0.35),
        "sel": css_rgba(c["accent"], 0.32),
        "hover": css_rgba(c["accent"], 0.14),
        "rubber": css_rgba(c["accent"], 0.18),
        "scroll": css_rgba(c["fg"], 0.25),
    }
    named3 = {
        "theme_bg_color": c["bg"], "theme_fg_color": c["fg"], "theme_base_color": c["bg"],
        "theme_text_color": c["fg"], "theme_selected_bg_color": c["accent"],
        "theme_selected_fg_color": c["bg"], "accent_color": c["accent"],
        "accent_bg_color": c["accent"], "accent_fg_color": c["bg"],
        "borders": v["border"], "headerbar_bg_color": c["bg2"], "headerbar_fg_color": c["fg"],
        "popover_bg_color": c["bg2"], "popover_fg_color": c["fg"],
        "error_color": c["crit"], "warning_color": c["warn"], "success_color": c["good"],
    }
    named4 = {
        **named3,
        "window_bg_color": c["bg"], "window_fg_color": c["fg"],
        "view_bg_color": c["bg"], "view_fg_color": c["fg"],
        "sidebar_bg_color": v["sidebar"], "sidebar_fg_color": c["fg"],
        "card_bg_color": c["bg2"], "card_fg_color": c["fg"],
        "dialog_bg_color": c["bg2"], "dialog_fg_color": c["fg"],
        "destructive_bg_color": c["crit"], "destructive_color": c["crit"],
    }
    defs3 = "".join(f"@define-color {k} {val};\n" for k, val in named3.items())
    defs4 = "".join(f"@define-color {k} {val};\n" for k, val in named4.items())
    rules = GTK_COMMON.format(**v)
    head = f"/* Тема «{t['name']}» поверх Graphite-Dark. {GENERATED} */\n"
    write(HOME / ".config/gtk-3.0/gtk.css", head + defs3 + rules)
    base4 = "/usr/share/themes/Graphite-Dark/gtk-4.0"
    for fname in ("gtk.css", "gtk-dark.css"):
        write(HOME / ".config/gtk-4.0" / fname,
              head + f'@import url("file://{base4}/{fname}");\n' + defs4 + rules)


def reload_gtk():
    # GTK3 only rereads the user gtk.css when the theme name changes, so bounce it.
    try:
        cur = subprocess.run(["gsettings", "get", "org.gnome.desktop.interface", "gtk-theme"],
                             capture_output=True, text=True, timeout=5).stdout.strip().strip("'")
        if cur:
            subprocess.run(["gsettings", "set", "org.gnome.desktop.interface", "gtk-theme", "Adwaita"], timeout=5)
            subprocess.run(["gsettings", "set", "org.gnome.desktop.interface", "gtk-theme", cur], timeout=5)
        # File chooser dialogs (Code - OSS, browsers, ...) come from this portal; it does not
        # follow the bounce above, so restart it. It is D-Bus activated, nothing is lost.
        subprocess.run(["systemctl", "--user", "try-restart", "xdg-desktop-portal-gtk.service"], timeout=10)
    except (OSError, subprocess.SubprocessError):
        pass


DRIFT_BEGIN = "# >>> hypr themes (themegen.py) >>>"
DRIFT_END = "# <<< hypr themes (themegen.py) <<<"


def drift_path():
    return HOME / ".config/drift/config.toml"


def drift_set_engine_theme(text, name):
    if re.search(r"^\[engine\]", text, re.M) is None:
        return f'[engine]\ntheme = "{name}"\n\n' + text
    engine = re.search(r"^\[engine\][^\[]*", text, re.M)
    section = engine.group(0)
    if re.search(r"^theme\s*=", section, re.M):
        new = re.sub(r'^theme\s*=.*$', f'theme = "{name}"', section, count=1, flags=re.M)
    else:
        new = section.replace("[engine]\n", f'[engine]\ntheme = "{name}"\n', 1)
    return text[:engine.start()] + new + text[engine.end():]


def gen_drift_active(t):
    p = drift_path()
    text = p.read_text() if p.exists() else ""
    write(p, drift_set_engine_theme(text, t["name"]))


def vscode_settings_path():
    return HOME / ".config/Code - OSS/User/settings.json"


def vscode_label(t):
    return f"Hypr {t['label']}"


def gen_vscode_active(t):
    p = vscode_settings_path()
    if not p.exists():
        return
    text = p.read_text()
    label = vscode_label(t)
    c = t["c"]
    # Branch lines in Git Graph follow the palette too.
    graph = [c["accent"], c["accent2"], c["good"], c["warn"], c["accent3"], c["crit"], c["muted"]]
    try:
        data = json.loads(text)
        data["workbench.colorTheme"] = label
        data["git-graph.graph.colours"] = graph
        p.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n")
    except json.JSONDecodeError:
        # settings.json with comments: patch the single key in place.
        if '"workbench.colorTheme"' in text:
            text = re.sub(r'"workbench\.colorTheme"\s*:\s*"[^"]*"',
                          f'"workbench.colorTheme": "{label}"', text, count=1)
        else:
            text = text.replace("{", f'{{\n  "workbench.colorTheme": "{label}",', 1)
        p.write_text(text)


ROOT_HELPER = "/usr/local/bin/hypr-theme-root"


def gen_system(t, wallpaper):
    """Folder colours and the SDDM login screen, through the sudo-allowed root helper."""
    if not Path(ROOT_HELPER).exists():
        return
    ui_path = THEMES / t["name"] / "ui.json"
    ui = json.loads(ui_path.read_text()) if ui_path.exists() else {}
    cmds = []
    folders = ui.get("folders")
    stamp = HOME / ".cache/hypr-theme-folders"
    # papirus-folders takes a few seconds; skip it when the colour does not change.
    if folders and (not stamp.exists() or stamp.read_text().strip() != folders):
        cmds.append(f"sudo -n {ROOT_HELPER} folders {folders} >/dev/null && echo {folders} > {stamp}")
    if wallpaper:
        c = t["c"]
        args = " ".join(shlex.quote(a) for a in (wallpaper, c["accent"], c["bg"], c["fg"], t["display"]))
        cmds.append(f"sudo -n {ROOT_HELPER} sddm {args}")
    if cmds:
        # Detached, so changetheme does not wait for the icon theme to be rewritten.
        subprocess.Popen(["sh", "-c", "; ".join(cmds)], start_new_session=True,
                         stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)


def offer_telegram_theme(t):
    # AyuGram/Telegram cannot be themed from outside: opening the file shows its preview with
    # an "Apply" button. Only offered when the client is running, so nothing pops up otherwise.
    theme = TELEGRAM_DIR / f"{t['name']}.tdesktop-theme"
    if not theme.exists():
        return
    for binary in ("AyuGram", "Telegram"):
        if subprocess.run(["pgrep", "-x", binary], capture_output=True).returncode == 0:
            subprocess.Popen([binary, "--", str(theme)], start_new_session=True,
                             stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
            return


def apply(name, wallpaper=None):
    t = load(name)
    # changetheme reloads Hyprland, which drops any screen shader; keep screen-fx in sync.
    (Path(os.environ.get("XDG_RUNTIME_DIR", "/tmp")) / "screen-fx-on").unlink(missing_ok=True)
    gen_hypr(t)
    gen_css_palette(t)
    gen_waybar(t)
    gen_kitty(t)
    gen_hyprlock(t, wallpaper)
    gen_gtk(t)
    gen_drift_active(t)
    gen_vscode_active(t)
    gen_system(t, wallpaper)
    offer_telegram_theme(t)
    reload_gtk()


# ---------- bundled outputs (all themes) ----------

def build_drift(themes):
    blocks = [DRIFT_BEGIN]
    for t in themes:
        c = t["c"]
        pal = [c["accent"], c["accent2"], c["accent3"], c["good"], c["warn"]]
        dim = [mix(x, c["bg"], 0.7) for x in pal]
        blocks.append(f"[theme.{t['name']}]")
        blocks.append(f'bright  = "{mix(c["fg"], "#ffffff", 0.5)}"')
        blocks.append("palette = [" + ", ".join(f'"{x}"' for x in pal) + "]")
        blocks.append("dim     = [" + ", ".join(f'"{x}"' for x in dim) + "]")
        blocks.append("")
    blocks.append(DRIFT_END)
    p = drift_path()
    text = p.read_text() if p.exists() else ""
    text = re.sub(re.escape(DRIFT_BEGIN) + r".*?" + re.escape(DRIFT_END) + r"\n?", "", text, flags=re.S)
    write(p, text.rstrip("\n") + ("\n\n" if text.strip() else "") + "\n".join(blocks) + "\n")


def vscode_theme(t):
    # palette.json may carry calmer editor-only colours under "code" (hacker does: all-green
    # text is unreadable for real work).
    c = {**t["c"], **t.get("code", {})}
    bg, bg2, fg, mu = c["bg"], c["bg2"], c["fg"], c["muted"]
    a1, a2, a3 = c["accent"], c["accent2"], c["accent3"]
    border = mix(bg2, mu, 0.3)
    sidebar = mix(bg, bg2, 0.5)
    colors = {
        "focusBorder": a1, "foreground": fg, "descriptionForeground": mu,
        "selection.background": alpha(a1, 0.35), "widget.shadow": "#00000066",
        "editor.background": bg, "editor.foreground": fg,
        "editorCursor.foreground": a1, "editor.selectionBackground": alpha(a1, 0.28),
        "editor.inactiveSelectionBackground": alpha(a1, 0.14),
        "editor.selectionHighlightBackground": alpha(a2, 0.16),
        "editor.wordHighlightBackground": alpha(a2, 0.14),
        "editor.findMatchBackground": alpha(c["warn"], 0.35),
        "editor.findMatchHighlightBackground": alpha(c["warn"], 0.18),
        "editor.lineHighlightBackground": alpha(bg2, 0.8),
        "editorLineNumber.foreground": mix(mu, bg, 0.35), "editorLineNumber.activeForeground": a1,
        "editorIndentGuide.background1": alpha(mu, 0.18), "editorIndentGuide.activeBackground1": alpha(a1, 0.5),
        "editorBracketMatch.background": alpha(a1, 0.2), "editorBracketMatch.border": a1,
        "editorWhitespace.foreground": alpha(mu, 0.3),
        "editorGutter.addedBackground": c["good"], "editorGutter.modifiedBackground": c["warn"],
        "editorGutter.deletedBackground": c["crit"],
        "editorError.foreground": c["crit"], "editorWarning.foreground": c["warn"],
        "editorInfo.foreground": a2,
        "editorWidget.background": bg2, "editorWidget.border": border,
        "editorSuggestWidget.background": bg2, "editorSuggestWidget.selectedBackground": alpha(a1, 0.3),
        "editorSuggestWidget.highlightForeground": a1, "editorHoverWidget.background": bg2,
        "editorGroupHeader.tabsBackground": sidebar, "editorGroup.border": border,
        "tab.activeBackground": bg, "tab.activeForeground": fg, "tab.activeBorderTop": a1,
        "tab.inactiveBackground": sidebar, "tab.inactiveForeground": mu, "tab.border": border,
        "tab.hoverBackground": bg2,
        "titleBar.activeBackground": sidebar, "titleBar.activeForeground": fg,
        "titleBar.inactiveBackground": sidebar, "titleBar.inactiveForeground": mu,
        "activityBar.background": sidebar, "activityBar.foreground": a1,
        "activityBar.inactiveForeground": mu, "activityBar.activeBorder": a1,
        "activityBarBadge.background": a1, "activityBarBadge.foreground": bg,
        "sideBar.background": sidebar, "sideBar.foreground": fg, "sideBar.border": border,
        "sideBarSectionHeader.background": sidebar, "sideBarTitle.foreground": mu,
        "list.activeSelectionBackground": alpha(a1, 0.3), "list.activeSelectionForeground": fg,
        "list.inactiveSelectionBackground": alpha(a1, 0.16), "list.hoverBackground": alpha(a1, 0.1),
        "list.focusOutline": a1, "list.highlightForeground": a1,
        "statusBar.background": sidebar, "statusBar.foreground": mu, "statusBar.border": border,
        "statusBar.debuggingBackground": a3, "statusBar.debuggingForeground": fg,
        "statusBarItem.remoteBackground": a1, "statusBarItem.remoteForeground": bg,
        "panel.background": bg, "panel.border": border,
        "panelTitle.activeBorder": a1, "panelTitle.activeForeground": fg, "panelTitle.inactiveForeground": mu,
        "input.background": bg2, "input.foreground": fg, "input.border": border,
        "input.placeholderForeground": mu, "inputOption.activeBorder": a1,
        "dropdown.background": bg2, "dropdown.border": border,
        "button.background": a1, "button.foreground": bg, "button.hoverBackground": a2,
        "button.secondaryBackground": bg2, "button.secondaryForeground": fg,
        "badge.background": a1, "badge.foreground": bg,
        "progressBar.background": a1, "textLink.foreground": a1, "textLink.activeForeground": a2,
        "scrollbarSlider.background": alpha(fg, 0.12), "scrollbarSlider.hoverBackground": alpha(fg, 0.22),
        "scrollbarSlider.activeBackground": alpha(a1, 0.5),
        "menu.background": bg2, "menu.foreground": fg, "menu.selectionBackground": alpha(a1, 0.3),
        "quickInput.background": bg2, "quickInputList.focusBackground": alpha(a1, 0.3),
        "notifications.background": bg2, "notificationCenterHeader.background": sidebar,
        "terminal.background": bg, "terminal.foreground": fg, "terminalCursor.foreground": a1,
        "terminal.ansiBlack": bg2, "terminal.ansiRed": c["crit"], "terminal.ansiGreen": c["good"],
        "terminal.ansiYellow": c["warn"], "terminal.ansiBlue": a1, "terminal.ansiMagenta": a3,
        "terminal.ansiCyan": a2, "terminal.ansiWhite": fg,
        "terminal.ansiBrightBlack": mu, "terminal.ansiBrightRed": mix(c["crit"], "#ffffff", 0.2),
        "terminal.ansiBrightGreen": mix(c["good"], "#ffffff", 0.2),
        "terminal.ansiBrightYellow": mix(c["warn"], "#ffffff", 0.2),
        "terminal.ansiBrightBlue": a2, "terminal.ansiBrightMagenta": mix(a3, "#ffffff", 0.25),
        "terminal.ansiBrightCyan": mix(a2, "#ffffff", 0.25), "terminal.ansiBrightWhite": "#ffffff",
        "gitDecoration.modifiedResourceForeground": c["warn"],
        "gitDecoration.untrackedResourceForeground": c["good"],
        "gitDecoration.deletedResourceForeground": c["crit"],
        "gitDecoration.ignoredResourceForeground": mix(mu, bg, 0.3),
        "breadcrumb.foreground": mu, "breadcrumb.focusForeground": fg,
        "peekView.border": a1, "peekViewEditor.background": bg2, "peekViewResult.background": sidebar,
    }

    def tok(scope, color, style=None):
        s = {"foreground": color}
        if style:
            s["fontStyle"] = style
        return {"scope": scope, "settings": s}

    token_colors = [
        tok(["comment", "punctuation.definition.comment"], mix(mu, bg, 0.1), "italic"),
        tok(["keyword", "storage.type", "storage.modifier", "keyword.control"], a1),
        tok(["keyword.operator", "punctuation"], mix(fg, mu, 0.4)),
        tok(["string", "string.quoted", "markup.inline.raw"], c["good"]),
        tok(["constant.character.escape", "string.regexp"], c["warn"]),
        tok(["constant.numeric", "constant.language", "constant.other"], c["warn"]),
        tok(["entity.name.function", "support.function", "meta.function-call"], a2),
        tok(["entity.name.type", "entity.name.class", "support.type", "support.class",
             "entity.other.inherited-class"], mix(a2, fg, 0.35)),
        tok(["variable", "meta.definition.variable"], fg),
        tok(["variable.parameter"], mix(fg, a2, 0.3), "italic"),
        tok(["variable.other.property", "variable.other.object.property", "support.variable.property"],
            mix(fg, a1, 0.25)),
        tok(["entity.name.tag"], a1),
        tok(["entity.other.attribute-name"], a2, "italic"),
        tok(["storage.type.annotation", "meta.annotation", "entity.name.function.decorator"], a3),
        tok(["markup.heading", "entity.name.section"], a1, "bold"),
        tok(["markup.bold"], fg, "bold"), tok(["markup.italic"], fg, "italic"),
        tok(["markup.underline.link"], a2),
        tok(["invalid"], c["crit"]),
    ]
    return {"name": vscode_label(t), "type": "dark", "colors": colors, "tokenColors": token_colors,
            "semanticHighlighting": True}


def build_vscode(themes):
    out = HYPR / "build/vscode"
    shutil.rmtree(out, ignore_errors=True)
    ext = out / "extension"
    (ext / "themes").mkdir(parents=True)
    contributes = []
    for t in themes:
        (ext / "themes" / f"{t['name']}.json").write_text(json.dumps(vscode_theme(t), indent=2))
        contributes.append({"label": vscode_label(t), "uiTheme": "vs-dark",
                            "path": f"./themes/{t['name']}.json"})
    publisher, name = VSCODE_EXT_ID.split(".")
    pkg = {"name": name, "displayName": "Hypr Themes", "publisher": publisher,
           "version": VSCODE_EXT_VERSION, "description": "Color themes generated from the Hyprland palettes",
           "engines": {"vscode": "^1.60.0"}, "categories": ["Themes"],
           "contributes": {"themes": contributes}}
    (ext / "package.json").write_text(json.dumps(pkg, indent=2))
    manifest = f"""<?xml version="1.0" encoding="utf-8"?>
<PackageManifest Version="2.0.0" xmlns="http://schemas.microsoft.com/developer/vsx-schema/2011">
  <Metadata>
    <Identity Language="en-US" Id="{name}" Version="{VSCODE_EXT_VERSION}" Publisher="{publisher}"/>
    <DisplayName>Hypr Themes</DisplayName>
    <Description xml:space="preserve">Color themes generated from the Hyprland palettes</Description>
    <Categories>Themes</Categories>
    <Properties>
      <Property Id="Microsoft.VisualStudio.Code.Engine" Value="^1.60.0"/>
    </Properties>
  </Metadata>
  <Installation><InstallationTarget Id="Microsoft.VisualStudio.Code"/></Installation>
  <Dependencies/>
  <Assets>
    <Asset Type="Microsoft.VisualStudio.Code.Manifest" Path="extension/package.json" Addressable="true"/>
  </Assets>
</PackageManifest>
"""
    content_types = """<?xml version="1.0" encoding="utf-8"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension=".json" ContentType="application/json"/>
  <Default Extension=".vsixmanifest" ContentType="text/xml"/>
</Types>
"""
    vsix = out / f"{name}-{VSCODE_EXT_VERSION}.vsix"
    with zipfile.ZipFile(vsix, "w", zipfile.ZIP_DEFLATED) as z:
        z.writestr("[Content_Types].xml", content_types)
        z.writestr("extension.vsixmanifest", manifest)
        for f in ext.rglob("*"):
            if f.is_file():
                z.write(f, "extension/" + str(f.relative_to(ext)))
    if shutil.which("code-oss"):
        subprocess.run(["code-oss", "--install-extension", str(vsix), "--force"], check=False)
    return vsix


def neohtop_colors(t):
    c = t["c"]
    bg, bg2, fg, mu = c["bg"], c["bg2"], c["fg"], c["muted"]
    return {
        "base": bg, "mantle": mix(bg, "#000000", 0.15), "crust": mix(bg, "#000000", 0.3),
        "text": fg, "subtext0": mu, "subtext1": mix(mu, fg, 0.4),
        "surface0": bg2, "surface1": mix(bg2, mu, 0.2), "surface2": mix(bg2, mu, 0.4),
        "overlay0": mix(mu, bg, 0.2), "overlay1": mu,
        "blue": c["accent"], "lavender": c["accent2"], "sapphire": c["accent3"], "sky": c["accent2"],
        "red": c["crit"], "maroon": mix(c["crit"], fg, 0.25), "peach": mix(c["warn"], c["crit"], 0.35),
        "yellow": c["warn"], "green": c["good"], "teal": mix(c["good"], c["accent2"], 0.5),
    }


def build_neohtop(themes):
    repo = HOME / "neohtop"
    if not repo.exists():
        return None
    entries = []
    for t in themes:
        colors = "\n".join(f'      {k}: "{v}",' for k, v in neohtop_colors(t).items())
        entries.append(f'  {t["name"]}: {{\n    name: "{t["name"]}",\n    label: "{t["label"]}",\n'
                       f'    colors: {{\n{colors}\n    }},\n  }},')
    text = ("// " + GENERATED + "\n"
            'import type { Theme } from "$lib/types";\n\n'
            "export const hyprThemes: Record<string, Theme> = {\n" + "\n".join(entries) + "\n};\n")
    path = repo / "src/lib/definitions/hyprThemes.ts"
    write(path, text)
    return path


TELEGRAM_DIR = HOME / ".local/share/hypr-themes/telegram"


def telegram_colors(t):
    c = {**t["c"], **t.get("code", {})}
    bg, bg2, fg, mu = c["bg"], c["bg2"], c["fg"], c["muted"]
    a1, a2 = c["accent"], c["accent2"]
    over = mix(bg, fg, 0.06)
    active = mix(bg, a1, 0.35)
    out_bg = mix(bg2, a1, 0.28)
    return {
        "windowBg": bg, "windowFg": fg, "windowBgOver": over, "windowBgRipple": mix(bg, fg, 0.12),
        "windowFgOver": fg, "windowSubTextFg": mu, "windowSubTextFgOver": mix(mu, fg, 0.3),
        "windowBoldFg": fg, "windowBoldFgOver": fg, "windowBgActive": a1, "windowFgActive": bg,
        "windowActiveTextFg": a1, "windowShadowFg": "#000000", "windowShadowFgFallback": bg2,
        "shadowFg": "#00000040", "imageBg": "#000000", "imageBgTransparent": "#ffffff",
        "activeButtonBg": a1, "activeButtonBgOver": mix(a1, fg, 0.15), "activeButtonBgRipple": mix(a1, bg, 0.3),
        "activeButtonFg": bg, "activeButtonFgOver": bg, "activeButtonSecondaryFg": mix(bg, a1, 0.4),
        "activeButtonSecondaryFgOver": mix(bg, a1, 0.4), "activeLineFg": a1, "activeLineFgError": c["crit"],
        "lightButtonBg": bg, "lightButtonBgOver": over, "lightButtonBgRipple": mix(bg, a1, 0.2),
        "lightButtonFg": a1, "lightButtonFgOver": a1, "attentionButtonFg": c["crit"],
        "attentionButtonFgOver": c["crit"], "attentionButtonBgOver": mix(bg, c["crit"], 0.12),
        "outlineButtonBg": bg, "outlineButtonBgOver": over, "outlineButtonOutlineFg": a1,
        "menuBg": bg2, "menuBgOver": mix(bg2, fg, 0.07), "menuBgRipple": mix(bg2, fg, 0.12),
        "menuIconFg": mu, "menuIconFgOver": fg, "menuSubmenuArrowFg": mu, "menuFgDisabled": mix(mu, bg, 0.4),
        "menuSeparatorFg": mix(bg2, mu, 0.3), "scrollBarBg": f"{fg}55", "scrollBarBgOver": f"{fg}88",
        "scrollBg": f"{fg}11", "scrollBgOver": f"{fg}22", "smallCloseIconFg": mu, "smallCloseIconFgOver": fg,
        "radialFg": a1, "radialBg": f"{bg}88", "placeholderFg": mu, "placeholderFgActive": mix(mu, bg, 0.3),
        "inputBorderFg": mix(bg2, mu, 0.5), "filterInputBorderFg": a1, "filterInputInactiveBg": bg2,
        "filterInputActiveBg": bg, "checkboxFg": mu, "sliderBgInactive": mix(bg2, mu, 0.4), "sliderBgActive": a1,
        "tooltipBg": bg2, "tooltipFg": fg, "tooltipBorderFg": mix(bg2, mu, 0.3),
        "titleBg": bg2, "titleBgActive": bg2, "titleFg": mu, "titleFgActive": fg,
        "titleButtonFg": mu, "titleButtonFgOver": fg, "titleButtonBgOver": over,
        "trayCounterBg": a1, "trayCounterFg": bg, "layerBg": "#000000aa", "cancelIconFg": mu,
        "boxBg": bg2, "boxTextFg": fg, "boxTextFgGood": c["good"], "boxTextFgError": c["crit"],
        "boxTitleFg": fg, "boxSearchBg": bg2, "boxTitleAdditionalFg": mu, "boxTitleCloseFg": mu,
        "dialogsBg": bg, "dialogsNameFg": fg, "dialogsChatIconFg": fg, "dialogsDateFg": mu,
        "dialogsTextFg": mu, "dialogsTextFgService": a2, "dialogsDraftFg": c["crit"],
        "dialogsVerifiedIconBg": a1, "dialogsVerifiedIconFg": bg, "dialogsSendingIconFg": mu,
        "dialogsSentIconFg": a1, "dialogsUnreadBg": a1, "dialogsUnreadBgMuted": mu, "dialogsUnreadFg": bg,
        "dialogsBgOver": over, "dialogsBgActive": active, "dialogsNameFgActive": fg, "dialogsTextFgActive": fg,
        "dialogsDateFgActive": fg, "dialogsUnreadBgActive": fg, "dialogsUnreadFgActive": active,
        "dialogsRippleBg": mix(bg, a1, 0.2), "dialogsRippleBgActive": mix(active, fg, 0.15),
        "dialogsForwardBg": active, "dialogsForwardFg": fg,
        "searchedBarBg": bg2, "searchedBarFg": mu, "topBarBg": bg2,
        "historyTextInFg": fg, "historyTextOutFg": fg, "historyCaptionInFg": fg, "historyCaptionOutFg": fg,
        "msgInBg": bg2, "msgInBgSelected": mix(bg2, a1, 0.25), "msgOutBg": out_bg,
        "msgOutBgSelected": mix(out_bg, a1, 0.25), "msgInShadow": "#00000033", "msgOutShadow": "#00000033",
        "msgInServiceFg": a1, "msgOutServiceFg": a2, "msgInDateFg": mu, "msgOutDateFg": mix(mu, fg, 0.3),
        "msgFileInBg": a1, "msgFileOutBg": a2, "msgInReplyBarColor": a1, "msgOutReplyBarColor": a2,
        "historyLinkInFg": a2, "historyLinkOutFg": a2, "historyOutIconFg": a1,
        "msgServiceBg": f"{bg}aa", "msgServiceFg": fg, "historyComposeAreaBg": bg2, "historyComposeAreaFg": fg,
        "historyComposeIconFg": mu, "historyComposeIconFgOver": fg, "historySendIconFg": a1,
        "historySendIconFgOver": a2, "historyPinnedBg": bg2, "historyReplyBg": bg2, "historyReplyIconFg": a1,
        "historyToDownBg": bg2, "historyToDownFg": mu, "historyUnreadBarBg": bg2, "historyUnreadBarFg": a1,
        "sideBarBg": mix(bg, "#000000", 0.2), "sideBarBgActive": mix(bg, a1, 0.25), "sideBarTextFg": mu,
        "sideBarTextFgActive": fg, "sideBarIconFg": mu, "sideBarIconFgActive": a1, "sideBarBadgeBg": a1,
        "sideBarBadgeFg": bg, "emojiPanBg": bg2, "emojiPanCategories": bg2, "emojiIconFg": mu,
        "emojiIconFgActive": a1, "stickerPanDeleteBg": "#000000cc", "mainMenuBg": bg, "mainMenuCoverBg": bg2,
        "mainMenuCoverFg": fg, "notificationBg": bg2, "callBg": bg2, "callNameFg": fg, "callFingerprintBg": bg,
    }


def build_telegram(themes):
    TELEGRAM_DIR.mkdir(parents=True, exist_ok=True)
    for t in themes:
        body = "".join(f"{k}: {v};\n" for k, v in telegram_colors(t).items())
        walls = sorted(p for p in (THEMES / t["name"]).iterdir()
                       if p.suffix.lower() in (".png", ".jpg", ".jpeg", ".webp"))
        bg_bytes = None
        if walls:
            im = Image.open(walls[0]).convert("RGB")
            im.thumbnail((1920, 1080))
            im = ImageEnhance.Brightness(im.filter(ImageFilter.GaussianBlur(14))).enhance(0.45)
            buf = io.BytesIO()
            im.save(buf, "JPEG", quality=85)
            bg_bytes = buf.getvalue()
        path = TELEGRAM_DIR / f"{t['name']}.tdesktop-theme"
        with zipfile.ZipFile(path, "w", zipfile.ZIP_DEFLATED) as z:
            z.writestr("colors.tdesktop-theme", f"// Hypr {t['label']}. {GENERATED}\n" + body)
            if bg_bytes:
                z.writestr("background.jpg", bg_bytes)
    return TELEGRAM_DIR


# ---------- battery icons (custom/battery in waybar) ----------

CLAWD_IDLE = ["..XXXXXXXX..", "..XXXXXXXX..", "..XBXXXXBX..", "XXXBXXXXBXXX",
              "XXXXXXXXXXXX", "..XXXXXXXX..", "..X.X..X.X..", "..X.X..X.X.."]
CLAWD_WAVE = ["..XXXXXXXX.X", "..XXXXXXXX.X", "..XBXXXXBXX.", "XXXBXXXXBX..",
              "XXXXXXXXXX..", "..XXXXXXXX..", "..X.X..X.X..", "..X.X..X.X.."]


def svg(body, view="0 0 24 24"):
    return f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="{view}">{body}</svg>'


def pixel_art(grid, body, eyes):
    rects = []
    for y, row in enumerate(grid):
        for x, ch in enumerate(row):
            if ch in "XB":
                rects.append(f'<rect x="{x}" y="{y}" width="1.02" height="1.02" fill="{body if ch == "X" else eyes}"/>')
    return svg("".join(rects), "0 -2 12 12")


def sparkle(x, y, r, color):
    # Four-pointed star.
    return (f'<path d="M{x} {y - r} L{x + r * 0.28} {y - r * 0.28} L{x + r} {y} L{x + r * 0.28} {y + r * 0.28} '
            f'L{x} {y + r} L{x - r * 0.28} {y + r * 0.28} L{x - r} {y} L{x - r * 0.28} {y - r * 0.28} Z" fill="{color}"/>')


def battery_frames(t):
    c = t["c"]
    name = t["name"]
    if name == "claude":
        return [pixel_art(CLAWD_IDLE, c["accent"], c["bg"]), pixel_art(CLAWD_WAVE, c["accent"], c["bg"])]
    if name == "frieren":
        # Frieren's staff: a thin diagonal shaft, a collar ring, and a spiral crook with two
        # small knobs on top.
        cx, cy = 16.2, 5.6
        pts = []
        for i in range(61):
            a = math.pi * 0.62 + i / 60 * math.pi * 3.1   # start at the bottom-left, wind inwards
            r = 4.1 - i / 60 * 3.4
            pts.append(f"{cx + r * math.cos(a):.2f},{cy + r * math.sin(a):.2f}")
        wood, metal = c["accent3"], c["accent2"]
        staff = (f'<line x1="6.4" y1="22.6" x2="14.6" y2="9.4" stroke="{wood}" stroke-width="1.5" stroke-linecap="round"/>'
                 f'<line x1="13.5" y1="9.6" x2="15.6" y2="10.9" stroke="{metal}" stroke-width="1.6" stroke-linecap="round"/>'
                 f'<polyline points="{" ".join(pts)}" fill="none" stroke="{metal}" stroke-width="1.5" '
                 f'stroke-linecap="round" stroke-linejoin="round"/>'
                 f'<circle cx="12.3" cy="2.6" r="0.75" fill="{metal}"/>'
                 f'<circle cx="20.1" cy="2.8" r="0.75" fill="{metal}"/>'
                 f'<circle cx="6.2" cy="22.9" r="0.9" fill="{metal}"/>')
        return [svg(staff),
                svg(staff + sparkle(4.5, 4, 2.4, c["accent2"]) + sparkle(19.5, 10, 1.8, c["fg"])),
                svg(staff + sparkle(21.5, 9, 2.4, c["accent2"]) + sparkle(5, 12, 1.8, c["fg"]))]
    if name == "hacker":
        frame = (f'<rect x="2" y="4" width="20" height="16" rx="1" fill="none" stroke="{c["accent"]}" stroke-width="1.6"/>'
                 f'<path d="M6 9 L9.5 12 L6 15" fill="none" stroke="{c["accent"]}" stroke-width="1.8"/>')
        cursor = f'<rect x="11" y="14" width="6" height="1.8" fill="{c["accent2"]}"/>'
        return [svg(frame + cursor), svg(frame)]
    if name == "cyberpunk":
        bolt = "M13.5 2 L5 13.5 H11 L9.5 22 L19 9.5 H13 Z"
        idle = svg(f'<path d="{bolt}" fill="{c["accent"]}"/>')
        glitch = svg(f'<path d="{bolt}" fill="{c["accent2"]}" transform="translate(1.6 0)" opacity="0.85"/>'
                     f'<path d="{bolt}" fill="{c["accent"]}" transform="translate(-1.6 0.6)" opacity="0.85"/>'
                     f'<rect x="3" y="11" width="18" height="1.4" fill="{c["bg"]}"/>')
        return [idle, glitch]
    if name == "sakura":
        # Cherry blossom: five notched petals. On click it turns by one petal (72°) while a
        # loose petal tumbles down past its right side.
        petal = "M0 0 C-3.3 -2.2 -3.5 -6.6 -1.3 -8 L0 -6.9 L1.3 -8 C3.5 -6.6 3.3 -2.2 0 0 Z"

        def blossom(rot, fall=None):
            body = "".join(f'<path d="{petal}" fill="{c["accent"]}" stroke="{c["accent2"]}" stroke-width="0.5" '
                           f'transform="translate(11 11) rotate({rot + k * 72})"/>' for k in range(5))
            body += (f'<circle cx="11" cy="11" r="1.9" fill="{c["accent3"]}"/>'
                     f'<circle cx="11" cy="11" r="0.8" fill="{c["warn"]}"/>')
            if fall:
                x, y, a, op = fall
                body += (f'<path d="{petal}" fill="{c["accent"]}" opacity="{op}" '
                         f'transform="translate({x} {y}) rotate({a}) scale(0.5)"/>')
            return svg(body)

        frames = [blossom(0)]
        for i in range(1, 6):
            t = i / 5
            frames.append(blossom(72 * t * t * (3 - 2 * t),
                                  (18.5 + 2.2 * math.sin(t * math.pi * 2), 8 + 14 * t, 40 + 260 * t, round(1 - 0.5 * t, 2))))
        return frames
    if name == "coffee":
        # A cup on a saucer; on click two wisps of steam rise and fade out.
        cup = (f'<path d="M4.5 11 H16.5 V14.6 C16.5 18.4 14 20 10.5 20 C7 20 4.5 18.4 4.5 14.6 Z" fill="{c["accent"]}"/>'
               f'<path d="M16.4 12.4 C20.4 12.4 20.4 17.4 16.2 17.4" fill="none" stroke="{c["accent"]}" stroke-width="1.6"/>'
               f'<ellipse cx="10.5" cy="11" rx="6" ry="1.1" fill="{c["accent3"]}"/>'
               f'<line x1="2.8" y1="21.4" x2="18.2" y2="21.4" stroke="{c["accent2"]}" stroke-width="1.4" stroke-linecap="round"/>')
        wisp = "M0 8 C-1.3 6.6 1.3 5.4 0 4 C-1.3 2.6 1.3 1.4 0 0"

        def steam(x, dy, op):
            return (f'<path d="{wisp}" fill="none" stroke="{c["fg"]}" stroke-width="1.2" stroke-linecap="round" '
                    f'opacity="{op}" transform="translate({x} {dy})"/>')

        frames = [svg(cup)]
        for i in range(1, 6):
            t = i / 5
            # The second wisp trails the first a little.
            a, b = t, max(0.0, t - 0.2) / 0.8
            op = lambda u: round(math.sin(min(1, u) * math.pi) * 0.95, 2)
            frames.append(svg(cup + steam(8.5, 3 - 4.5 * a, op(a)) + steam(12.5, 3.5 - 4.5 * b, op(b))))
        return frames
    if name == "ocean":
        # Jellyfish: on click the bell squeezes and the whole body pushes up (frames 1..4),
        # then relaxes back (pingpong).
        def jelly(t):
            e = t * t * (3 - 2 * t)
            a, h, yb = 7 - 1.4 * e, 6.5 + 1 * e, 11.5 - 2 * e
            top = yb - h * 1.33
            bell = (f'M{12 - a:.2f} {yb:.2f} C{12 - a:.2f} {top:.2f} {12 + a:.2f} {top:.2f} {12 + a:.2f} {yb:.2f} '
                    f'Q{12 + a / 2:.2f} {yb + 1.3:.2f} 12 {yb:.2f} Q{12 - a / 2:.2f} {yb + 1.3:.2f} {12 - a:.2f} {yb:.2f} Z')
            ln = 9 + 1.5 * e
            tent = ""
            for k, x0 in enumerate((-0.6, -0.2, 0.2, 0.6)):
                x = 12 + x0 * a * 1.1
                sway = (1.2 - 0.8 * e) * (1 if k % 2 else -1)
                tent += (f'<path d="M{x:.2f} {yb + 0.6:.2f} C{x + sway:.2f} {yb + ln * 0.35:.2f} {x - sway:.2f} {yb + ln * 0.65:.2f} '
                         f'{x + sway * 0.5:.2f} {yb + ln:.2f}" fill="none" stroke="{c["accent2"]}" stroke-width="1" '
                         f'stroke-linecap="round" opacity="0.85"/>')
            return svg(f'<defs><linearGradient id="g" x1="0" y1="0" x2="0" y2="1">'
                       f'<stop offset="0" stop-color="{c["accent"]}"/><stop offset="1" stop-color="{c["accent2"]}"/>'
                       f'</linearGradient></defs>'
                       f'{tent}<path d="{bell}" fill="url(#g)" opacity="0.92"/>'
                       f'<ellipse cx="12" cy="{yb - h * 0.45:.2f}" rx="{a * 0.4:.2f}" ry="{h * 0.22:.2f}" fill="{c["fg"]}" opacity="0.45"/>')
        return [jelly(i / 4) for i in range(5)]
    # night: the crescent fills up to a full moon (frames 1..6) and wanes back on click.
    def moon(t):
        # Shadow disc (r=8) slides along the crescent's axis from 5.8 to 17 units away from the
        # moon's centre: 17 = 9 + 8, where it stops touching the disc and the moon is full.
        e = t * t * (3 - 2 * t)
        d = 5.83 + e * (17 - 5.83)
        sx, sy = 12 + d * 5 / 5.83, 12 - d * 3 / 5.83
        return svg(f'<defs><mask id="m"><rect width="24" height="24" fill="white"/>'
                   f'<circle cx="{sx:.2f}" cy="{sy:.2f}" r="8" fill="black"/></mask></defs>'
                   f'<circle cx="12" cy="12" r="9" fill="{c["fg"]}" mask="url(#m)"/>')
    return [moon(i / 6) for i in range(7)]


def build_battery_icons(themes):
    for t in themes:
        d = THEMES / t["name"] / "assets"
        d.mkdir(parents=True, exist_ok=True)
        for old in d.glob("battery-*.svg"):
            old.unlink()
        for i, frame in enumerate(battery_frames(t)):
            (d / f"battery-{i}.svg").write_text(frame)


def build():
    themes = [load(n) for n in all_themes()]
    build_drift(themes)
    print("vscode:", build_vscode(themes))
    print("neohtop:", build_neohtop(themes))
    print("telegram:", build_telegram(themes))
    build_battery_icons(themes)
    cur = (HYPR / "current-theme")
    if cur.exists():
        gen_drift_active(load(cur.read_text().strip()))


def main(argv):
    if len(argv) >= 2 and argv[0] == "apply":
        wp = None
        if "--wallpaper" in argv:
            wp = argv[argv.index("--wallpaper") + 1] or None
        apply(argv[1], wp)
    elif argv[:1] == ["build"]:
        build()
    else:
        print(__doc__.strip(), file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
